spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
cloudinary.cloud_name=dnfznhucd
cloudinary.api_key=866264271662951
cloudinary.api_secret=CP7hYmthX9hlr_9rFumZygqTw1o

#spring.application.name=Springboot_tesing
#spring.datasource.url=jdbc:mysql://localhost:3366/springboot
#spring.datasource.username=root
#spring.datasource.password=arvind
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.thymeleaf.cache=false
#spring.thymeleaf.suffix=.html
#
#cloudinary.cloud_name=dnfznhucd
#cloudinary.api_key=866264271662951
#cloudinary.api_secret=CP7hYmthX9hlr_9rFumZygqTw1o
#
#server.port=8182